# Auto-generated URL mapping file
URL_MAPPING = {
  "About Us": "https://www.morehouse.org.uk/our-school/our-ethos/",
  "Academic Life": "https://www.morehouse.org.uk/learning/academic-life/",
  "Admissions": "https://www.morehouse.org.uk/admissions/",
  "Be More": "https://www.morehouse.org.uk/learning/be-more/",
  "Book an Open Morning": "https://www.morehouse.org.uk/admissions/our-open-events/",
  "City Curriculum": "https://www.morehouse.org.uk/beyond-the-classroom/city-curriculum/",
  "Co-curricular Programme": "https://www.morehouse.org.uk/beyond-the-classroom/co-curricular-programme/",
  "Contact Us": "https://www.morehouse.org.uk/contact/",
  "Contact us": "https://www.morehouse.org.uk/contact/",
  "Cookie Usage": "https://www.morehouse.org.uk/cookie-usage/",
  "E-Safety": "https://www.morehouse.org.uk/e-safety/",
  "Enquire Now": "https://www.morehouse.org.uk/admissions/enquiry/",
  "Equity, Diversity and Inclusion (EDI)": "https://www.morehouse.org.uk/our-school/equity-diversity-and-inclusion-edi/",
  "Faith Life": "https://www.morehouse.org.uk/beyond-the-classroom/faith-life/",
  "Fees": "https://www.morehouse.org.uk/admissions/fees/",
  "Get directions": "https://www.morehouse.org.uk",
  "Head Girl\u2019s Podcast": "https://www.morehouse.org.uk/?page_id=5560",
  "Here": "https://www.morehouse.org.uk/admissions/our-open-events/",
  "History": "https://www.morehouse.org.uk/our-school/history/",
  "Houses": "https://www.morehouse.org.uk/our-school/houses/",
  "Inspection Reports": "https://www.morehouse.org.uk/information/inspection-reports/",
  "International Applications and Visas": "https://www.morehouse.org.uk/international-applications-and-visas/",
  "Learning Support": "https://www.morehouse.org.uk/learning/learning-support/",
  "Lettings": "https://www.morehouse.org.uk/information/lettings/",
  "Lunch": "https://www.morehouse.org.uk/information/school-lunches/",
  "MHS Films": "https://www.morehouse.org.uk/mhs-films/",
  "Meet The Head": "https://www.morehouse.org.uk/our-school/meet-the-head/",
  "Meet the Head": "https://www.morehouse.org.uk/our-school/meet-the-head/",
  "More House": "https://www.morehouse.org.uk/",
  "More House School": "https://www.morehouse.org.uk/",
  "More House Stories": "https://www.morehouse.org.uk/our-school/more-house-stories/",
  "News": "https://www.morehouse.org.uk/news-and-calendar/news/",
  "News and Updates": "https://www.morehouse.org.uk/news-and-updates/",
  "Our Creative Suite": "https://www.morehouse.org.uk/learning/our-creative-suite/",
  "Our Ethos": "https://www.morehouse.org.uk/our-school/our-ethos/",
  "Our Open Events": "https://www.morehouse.org.uk/admissions/our-open-events/",
  "Our Staff and Governors": "https://www.morehouse.org.uk/information/our-staff-and-governors/",
  "Partnerships": "https://www.morehouse.org.uk/partnerships/",
  "Pastoral Care": "https://www.morehouse.org.uk/our-school/pastoral-care/",
  "Pre-Senior": "https://www.morehouse.org.uk/pre-senior/",
  "Pre-Senior (Years 5 and 6)": "https://www.morehouse.org.uk/pre-senior/",
  "Privacy Policy": "https://www.morehouse.org.uk/privacy-policy/",
  "Publications and Head\u2019s Articles": "https://www.morehouse.org.uk/?page_id=944",
  "Read More": "https://www.morehouse.org.uk/news-and-calendar/news_post/ks3-production-antigone/",
  "Read more": "https://www.morehouse.org.uk/our-school/pastoral-care/",
  "Reporting safeguarding concerns and resources": "https://www.morehouse.org.uk/reporting-safeguarding-concerns-and-resources/",
  "Results and Destinations": "https://www.morehouse.org.uk/learning/results-and-destinations/",
  "Safeguarding": "https://www.morehouse.org.uk/information/safeguarding/",
  "Scholarships and Bursaries": "https://www.morehouse.org.uk/admissions/scholarships-and-bursaries/",
  "School Calendar": "https://www.morehouse.org.uk/news-and-calendar/calendar/",
  "School Policies": "https://www.morehouse.org.uk/information/school-policies/",
  "School Uniform": "https://www.morehouse.org.uk/information/school-uniform/",
  "Senior School": "https://www.morehouse.org.uk/senior-school/",
  "Sixth Form": "https://www.morehouse.org.uk/learning/sixth-form/",
  "Sport": "https://www.morehouse.org.uk/beyond-the-classroom/sport/",
  "Subjects": "https://www.morehouse.org.uk/learning/subjects/",
  "Submit Your Enquiry": "https://www.morehouse.org.uk/admissions/enquiry/",
  "Term Dates": "https://www.morehouse.org.uk/news-and-calendar/term-dates/",
  "Terms of Use": "https://www.morehouse.org.uk/terms-of-use/",
  "Upcoming Events": "https://www.morehouse.org.uk/upcoming-events/",
  "Visit Us": "https://www.morehouse.org.uk/admissions/our-open-events/",
  "Watch Video": "https://www.morehouse.org.uk/news-and-calendar/heads-vlog/discover-sport/",
  "Your Admissions Journey": "https://www.morehouse.org.uk/admissions/joining-more-house/",
  "ethos": "https://www.morehouse.org.uk/our-school/our-ethos/",
  "enquiry": "https://www.morehouse.org.uk/admissions/enquiry/",
  "our community": "https://www.morehouse.org.uk/our-school/pastoral-care/",
  "the attached form": "https://www.morehouse.org.uk/wp-content/uploads/2021/08/3-342-fees-refund-scheme.docx"
}